# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  matlab: mathworks/matlab@0.7.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: artifacts/junit/testResults.xml
          test-results-pdf: artifacts/pdf/testResults.pdf
      - store_test_results:
          path: artifacts/junit
      - store_artifacts:
          path: artifacts

workflows:
  build:
    jobs:
      - build
